### PR TITLE
Made `ili occupy a predefined container

### PR DESCRIPTION
**Pull request by iprotsyuk**

### CODE REVIEW

**Comment by iprotsyuk** [comment]
I set a weird position of the `ili container so that you guys could check if it works fine in such a div. If it does, I'll make one more commit to expand the main container for the whole window.

**Comment by antgonza** [comment]
👍  looks great, even the dashed line is cool. I think it seems faster to load ...

**Comment by ElDeveloper** [comment]
👍

**Comment by ElDeveloper** [comment]
:shipit:

**Pull request merged**
